### feed simplified
GET http://localhost:3000/feed/simplified HTTP/1.1
Authorization: userhandle main-user

### new user
//normal data, empty main user
GET http://localhost:3000/bots/scenes/default

### fan of a topic
//normal data, the main user interacted with the "techonology" topic and follows related users
GET http://localhost:3000/bots/scenes/fan

### follow one simplified
//in this scene, the main user follows a specified user within a simplified environment.
GET http://localhost:3000/bots/scenes/followOneSimplifiedj

### follow one
//in this scene, the main user follows a specified user within a normal environment.
GET http://localhost:3000/bots/scenes/followOne