### users
GET http://localhost:3000/seed/users/10

### main user
GET http://localhost:3000/seed/users/main

### posts
GET http://localhost:3000/seed/posts/10

### likes
GET http://localhost:3000/seed/likes

### follows
GET http://localhost:3000/seed/follows/10