### focus post
GET http://localhost:3000/users/main-user/status/main-post

### register or login
POST http://localhost:3000/authenticate HTTP/1.1
content-type: application/json

{
    "handle": "new_user"
}