### new
GET http://localhost:3000/bots/userType/new

### follows one
GET http://localhost:3000/bots/userType/followsOne

### interacts with the posts of a topic
GET http://localhost:3000/bots/userType/interactTopic