### new
GET http://localhost:3000/bots/userType/new

### follows one

### follows multiple in a topic

### interacts with multiple within a topic

### follows and interacts with multiple within a topic